apiVersion: v1
kind: Secret
metadata:
  name: k8s-monitor-secrets
  namespace: k8s-monitor
  labels:
    app: k8s-monitor
type: Opaque
stringData:
  # IMPORTANT: Replace these with actual values!
  # These are placeholders and should be updated before deployment

  # Anthropic API Key (required)
  ANTHROPIC_API_KEY: "sk-ant-YOUR_KEY_HERE"

  # GitHub token for deployment correlation (required for Phase 5)
  GITHUB_TOKEN: "ghp_YOUR_TOKEN_HERE"

  # Slack bot token for notifications (required)
  SLACK_BOT_TOKEN: "xoxb-YOUR_TOKEN_HERE"

  # Slack channel where alerts should be posted (e.g., #oncall-agent or channel ID like C09LWTRDQUX)
  SLACK_CHANNEL: "#oncall-agent"
