apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-monitor
  namespace: k8s-monitor
  labels:
    app: k8s-monitor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-monitor
  labels:
    app: k8s-monitor
rules:
  # Pod access
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

  # Deployment access
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]

  # Service and Ingress access
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]

  # Node access
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # Event access
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

  # Certificate access (for TLS checks)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

  # Namespace access
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-monitor
  labels:
    app: k8s-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-monitor
subjects:
  - kind: ServiceAccount
    name: k8s-monitor
    namespace: k8s-monitor
