# ClusterRoleBinding (Production)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oncall-agent-reader-binding
  labels:
    app.kubernetes.io/instance: oncall-agent
    app.kubernetes.io/name: oncall-agent
    ballista/environment: prod
subjects:
  - kind: ServiceAccount
    name: oncall-agent-api-sa
    namespace: crossplane-oncall-agent
roleRef:
  kind: ClusterRole
  name: oncall-agent-reader
  apiGroup: rbac.authorization.k8s.io