[project]
name = "eks-monitoring-agent"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "claude-agent-sdk>=0.1.0",
    "requests>=2.31.0",
]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"
