# Kubernetes Monitoring Configuration
# On-Call Troubleshooting Agent

monitoring:
  clusters:
    - name: dev-eks
      namespaces:
        - default
        - artemis-preprod
        - proteus-preprod
        - proteus-celery-preprod
        - proteus-kafka-preprod
        - export-manager-preprod

      # Polling interval for events
      poll_interval_seconds: 300

  # Event filters - only these events trigger agent analysis
  event_filters:
    - type: Warning
      reasons:
        - OOMKilled
        - CrashLoopBackOff
        - ImagePullBackOff
        - FailedScheduling
        - Unhealthy
        - BackOff
        - Failed
        - FailedMount
        - NoCompatibleInstanceTypes

  # Alert rules with thresholds
  alert_rules:
    - name: pod-restart-threshold
      description: Pod restarting frequently
      condition: restart_count > 5
      severity: high

    - name: deployment-unavailable
      description: Deployment has insufficient replicas
      condition: available_replicas < desired_replicas
      severity: critical

    - name: oom-killer-active
      description: Pod killed due to out of memory
      condition: reason == "OOMKilled"
      severity: critical

    - name: crashloop-detected
      description: Pod in crash loop backoff
      condition: reason == "CrashLoopBackOff" AND restart_count > 3
      severity: high

    - name: image-pull-failure
      description: Unable to pull container image
      condition: reason == "ImagePullBackOff"
      severity: medium

    - name: karpenter-capacity-issue
      description: Karpenter cannot find compatible instance types
      condition: reason == "NoCompatibleInstanceTypes"
      severity: high

    - name: pod-unhealthy
      description: Pod failing health checks
      condition: reason == "Unhealthy"
      severity: high

    - name: failed-mount
      description: Volume mount failure
      condition: reason == "FailedMount"
      severity: high

    - name: scheduling-failure
      description: Pod cannot be scheduled
      condition: reason == "FailedScheduling"
      severity: high

  # Service criticality mapping
  service_criticality:
    critical:
      - proteus
      - proteus-kafka
      - artemis-auth
      - hermes
      - zeus
    high:
      - plutus-kafka-worker
      - export-manager
      - export-manager-kafka
