# Teams Notification Configuration
# Minimal config - only attributes actively used in code

teams_notifications:
  # Severity threshold for triggering notifications (high or critical)
  severity_threshold: high

  # Rate limiting to prevent notification spam
  rate_limiting:
    cooldown_minutes: 5
