# Service to Deployment Mapping
# Maps Kubernetes service names to GitHub repositories and service metadata

service_mappings:
  # Critical Services
  proteus:
    github_repo: artemishealth/proteus
    criticality: critical
    health_check_endpoint: /api/proteus/.well-known/ready

  proteus-kafka:
    github_repo: artemishealth/proteus
    criticality: critical
    health_check_endpoint: /api/proteus/.well-known/ready

  artemis-auth:
    github_repo: artemishealth/kleis
    k8s_deployment_name: artemis-auth
    criticality: critical
    health_check_endpoint: /health

  hermes:
    github_repo: artemishealth/hermes
    k8s_deployment_name: hermesapp
    criticality: critical
    health_check_endpoint: /

  zeus:
    github_repo: artemishealth/zeus
    k8s_deployment_name: zeus
    criticality: critical
    health_check_endpoint: /

  zeus-mara-http:
    github_repo: artemishealth/mara
    k8s_deployment_name: mara
    criticality: critical
    health_check_endpoint: /

  # High Priority Services
  export-manager:
    github_repo: artemishealth/content-export
    k8s_deployment_name: export-manager
    criticality: high

  plutus-kafka-worker:
    github_repo: artemishealth/plutus
    k8s_deployment_name: plutus-kafka-worker
    criticality: high

  export-manager-kafka:
    github_repo: artemishealth/content-export
    k8s_deployment_name: export-manager-kafka
    criticality: medium

  # Infrastructure Services
  karpenter:
    github_repo: kubernetes-sigs/karpenter
    criticality: high
